// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file spacex_api/device/account_shard.proto (package SpaceX.API.Device, syntax proto3)
 

import type { GenEnum, GenFile } from '@bufbuild/protobuf/codegenv1';
import { enumDesc, fileDesc } from '@bufbuild/protobuf/codegenv1';

/**
 * Describes the file spacex_api/device/account_shard.proto.
 */
export const file_spacex_api_device_account_shard: GenFile =
  /*@__PURE__*/
  fileDesc(
    'CiVzcGFjZXhfYXBpL2RldmljZS9hY2NvdW50X3NoYXJkLnByb3RvEhFTcGFjZVguQVBJLkRldmljZSpdCgxBY2NvdW50U2hhcmQSGQoVQUNDT1VOVF9TSEFSRF9VTktOT1dOEAASGQoVQUNDT1VOVF9TSEFSRF9ERUZBVUxUEAESFwoTQUNDT1VOVF9TSEFSRF9JTkRJQRACQiVaI3NwYWNleC5jb20vYXBpL2RldmljZS9hY2NvdW50X3NoYXJkYgZwcm90bzM'
  );

/**
 * @generated from enum SpaceX.API.Device.AccountShard
 */
export enum AccountShard {
  /**
   * @generated from enum value: ACCOUNT_SHARD_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: ACCOUNT_SHARD_DEFAULT = 1;
   */
  DEFAULT = 1,

  /**
   * @generated from enum value: ACCOUNT_SHARD_INDIA = 2;
   */
  INDIA = 2,
}

/**
 * Describes the enum SpaceX.API.Device.AccountShard.
 */
export const AccountShardSchema: GenEnum<AccountShard> =
  /*@__PURE__*/
  enumDesc(file_spacex_api_device_account_shard, 0);
