// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file spacex_api/device/command.proto (package SpaceX.API.Device, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spacex_api/device/command.proto.
 */
export const file_spacex_api_device_command: GenFile = /*@__PURE__*/
  fileDesc("Ch9zcGFjZXhfYXBpL2RldmljZS9jb21tYW5kLnByb3RvEhFTcGFjZVguQVBJLkRldmljZSJ4CglQdWJsaWNLZXkSCwoDa2V5GAEgASgJEjcKDGNhcGFiaWxpdGllcxgCIAMoDjIdLlNwYWNlWC5BUEkuRGV2aWNlLkNhcGFiaWxpdHlCAhgBEiUKBHVzZXIYAyABKA4yFy5TcGFjZVguQVBJLkRldmljZS5Vc2VyKtUBCgpDYXBhYmlsaXR5EggKBFJFQUQQABIRCg1SRUFEX0lOVEVSTkFMEA0SEAoMUkVBRF9QUklWQVRFEAcSCQoFTE9DQUwQDhIJCgVXUklURRABEhQKEFdSSVRFX1BFUlNJU1RFTlQQCxIJCgVERUJVRxACEgkKBUFETUlOEAMSCQoFU0VUVVAQBBILCgdTRVRfU0tVEAUSCwoHUkVGUkVTSBAGEggKBEZVU0UQCBIJCgVSRVNFVBAJEggKBFRFU1QQChIHCgNTU0gQDBIJCgVHVUVTVBAPKpABCgRVc2VyEgsKB05PX1VTRVIQABIHCgNHT0QQARIHCgNMQU4QAhIJCgVDTE9VRBADEgsKB0ZBQ1RPUlkQBBIKCgZST1VURVIQBRINCglHVUVTVF9MQU4QBhIYChRTRU5TSVRJVkVfQ09NTUFORElORxAHEgsKB0xBTl9UTFMQCBIPCgtDTE9VRF9JTkRJQRAJQhdaFXNwYWNleC5jb20vYXBpL2RldmljZWIGcHJvdG8z");

/**
 * @generated from message SpaceX.API.Device.PublicKey
 */
export type PublicKey = Message<"SpaceX.API.Device.PublicKey"> & {
  /**
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * @generated from field: repeated SpaceX.API.Device.Capability capabilities = 2 [deprecated = true];
   * @deprecated
   */
  capabilities: Capability[];

  /**
   * @generated from field: SpaceX.API.Device.User user = 3;
   */
  user: User;
};

/**
 * Describes the message SpaceX.API.Device.PublicKey.
 * Use `create(PublicKeySchema)` to create a new message.
 */
export const PublicKeySchema: GenMessage<PublicKey> = /*@__PURE__*/
  messageDesc(file_spacex_api_device_command, 0);

/**
 * @generated from enum SpaceX.API.Device.Capability
 */
export enum Capability {
  /**
   * @generated from enum value: READ = 0;
   */
  READ = 0,

  /**
   * @generated from enum value: READ_INTERNAL = 13;
   */
  READ_INTERNAL = 13,

  /**
   * @generated from enum value: READ_PRIVATE = 7;
   */
  READ_PRIVATE = 7,

  /**
   * @generated from enum value: LOCAL = 14;
   */
  LOCAL = 14,

  /**
   * @generated from enum value: WRITE = 1;
   */
  WRITE = 1,

  /**
   * @generated from enum value: WRITE_PERSISTENT = 11;
   */
  WRITE_PERSISTENT = 11,

  /**
   * @generated from enum value: DEBUG = 2;
   */
  DEBUG = 2,

  /**
   * @generated from enum value: ADMIN = 3;
   */
  ADMIN = 3,

  /**
   * @generated from enum value: SETUP = 4;
   */
  SETUP = 4,

  /**
   * @generated from enum value: SET_SKU = 5;
   */
  SET_SKU = 5,

  /**
   * @generated from enum value: REFRESH = 6;
   */
  REFRESH = 6,

  /**
   * @generated from enum value: FUSE = 8;
   */
  FUSE = 8,

  /**
   * @generated from enum value: RESET = 9;
   */
  RESET = 9,

  /**
   * @generated from enum value: TEST = 10;
   */
  TEST = 10,

  /**
   * @generated from enum value: SSH = 12;
   */
  SSH = 12,

  /**
   * @generated from enum value: GUEST = 15;
   */
  GUEST = 15,
}

/**
 * Describes the enum SpaceX.API.Device.Capability.
 */
export const CapabilitySchema: GenEnum<Capability> = /*@__PURE__*/
  enumDesc(file_spacex_api_device_command, 0);

/**
 * @generated from enum SpaceX.API.Device.User
 */
export enum User {
  /**
   * @generated from enum value: NO_USER = 0;
   */
  NO_USER = 0,

  /**
   * @generated from enum value: GOD = 1;
   */
  GOD = 1,

  /**
   * @generated from enum value: LAN = 2;
   */
  LAN = 2,

  /**
   * @generated from enum value: CLOUD = 3;
   */
  CLOUD = 3,

  /**
   * @generated from enum value: FACTORY = 4;
   */
  FACTORY = 4,

  /**
   * @generated from enum value: ROUTER = 5;
   */
  ROUTER = 5,

  /**
   * @generated from enum value: GUEST_LAN = 6;
   */
  GUEST_LAN = 6,

  /**
   * @generated from enum value: SENSITIVE_COMMANDING = 7;
   */
  SENSITIVE_COMMANDING = 7,

  /**
   * @generated from enum value: LAN_TLS = 8;
   */
  LAN_TLS = 8,

  /**
   * @generated from enum value: CLOUD_INDIA = 9;
   */
  CLOUD_INDIA = 9,
}

/**
 * Describes the enum SpaceX.API.Device.User.
 */
export const UserSchema: GenEnum<User> = /*@__PURE__*/
  enumDesc(file_spacex_api_device_command, 1);

