// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file spacex_api/device/dish_config.proto (package SpaceX.API.Device, syntax proto3)

import type { GenEnum, GenFile, GenMessage } from '@bufbuild/protobuf/codegenv1';
import { enumDesc, fileDesc, messageDesc } from '@bufbuild/protobuf/codegenv1';
import type { Message } from '@bufbuild/protobuf';

/**
 * Describes the file spacex_api/device/dish_config.proto.
 */
export const file_spacex_api_device_dish_config: GenFile =
  /*@__PURE__*/
  fileDesc(
    'CiNzcGFjZXhfYXBpL2RldmljZS9kaXNoX2NvbmZpZy5wcm90bxIRU3BhY2VYLkFQSS5EZXZpY2UilAcKCkRpc2hDb25maWcSQgoOc25vd19tZWx0X21vZGUYASABKA4yKi5TcGFjZVguQVBJLkRldmljZS5EaXNoQ29uZmlnLlNub3dNZWx0TW9kZRIdChRhcHBseV9zbm93X21lbHRfbW9kZRjpByABKAgSUAoVbG9jYXRpb25fcmVxdWVzdF9tb2RlGAIgASgOMjEuU3BhY2VYLkFQSS5EZXZpY2UuRGlzaENvbmZpZy5Mb2NhdGlvblJlcXVlc3RNb2RlEiQKG2FwcGx5X2xvY2F0aW9uX3JlcXVlc3RfbW9kZRjRDyABKAgSRAoPbGV2ZWxfZGlzaF9tb2RlGAMgASgOMisuU3BhY2VYLkFQSS5EZXZpY2UuRGlzaENvbmZpZy5MZXZlbERpc2hNb2RlEh4KFWFwcGx5X2xldmVsX2Rpc2hfbW9kZRi5FyABKAgSIAoYcG93ZXJfc2F2ZV9zdGFydF9taW51dGVzGAQgASgNEicKHmFwcGx5X3Bvd2VyX3NhdmVfc3RhcnRfbWludXRlcxihHyABKAgSIwobcG93ZXJfc2F2ZV9kdXJhdGlvbl9taW51dGVzGAUgASgNEioKIWFwcGx5X3Bvd2VyX3NhdmVfZHVyYXRpb25fbWludXRlcxiJJyABKAgSFwoPcG93ZXJfc2F2ZV9tb2RlGAYgASgIEh4KFWFwcGx5X3Bvd2VyX3NhdmVfbW9kZRjxLiABKAgSHAoUc3d1cGRhdGVfcmVib290X2hvdXIYCSABKA0SIwoaYXBwbHlfc3d1cGRhdGVfcmVib290X2hvdXIYqUYgASgIEisKI3N3dXBkYXRlX3RocmVlX2RheV9kZWZlcnJhbF9lbmFibGVkGAcgASgIEjIKKWFwcGx5X3N3dXBkYXRlX3RocmVlX2RheV9kZWZlcnJhbF9lbmFibGVkGNk2IAEoCBITCgthc3NldF9jbGFzcxgIIAEoDRIaChFhcHBseV9hc3NldF9jbGFzcxjBPiABKAgiNwoMU25vd01lbHRNb2RlEggKBEFVVE8QABINCglBTFdBWVNfT04QARIOCgpBTFdBWVNfT0ZGEAIiKgoTTG9jYXRpb25SZXF1ZXN0TW9kZRIICgROT05FEAASCQoFTE9DQUwQASI2Cg1MZXZlbERpc2hNb2RlEhQKEFRJTFRfTElLRV9OT1JNQUwQABIPCgtGT1JDRV9MRVZFTBABQhdaFXNwYWNleC5jb20vYXBpL2RldmljZWIGcHJvdG8z'
  );

/**
 * @generated from message SpaceX.API.Device.DishConfig
 */
export type DishConfig = Message<'SpaceX.API.Device.DishConfig'> & {
  /**
   * @generated from field: SpaceX.API.Device.DishConfig.SnowMeltMode snow_melt_mode = 1;
   */
  snowMeltMode: DishConfig_SnowMeltMode;

  /**
   * @generated from field: bool apply_snow_melt_mode = 1001;
   */
  applySnowMeltMode: boolean;

  /**
   * @generated from field: SpaceX.API.Device.DishConfig.LocationRequestMode location_request_mode = 2;
   */
  locationRequestMode: DishConfig_LocationRequestMode;

  /**
   * @generated from field: bool apply_location_request_mode = 2001;
   */
  applyLocationRequestMode: boolean;

  /**
   * @generated from field: SpaceX.API.Device.DishConfig.LevelDishMode level_dish_mode = 3;
   */
  levelDishMode: DishConfig_LevelDishMode;

  /**
   * @generated from field: bool apply_level_dish_mode = 3001;
   */
  applyLevelDishMode: boolean;

  /**
   * @generated from field: uint32 power_save_start_minutes = 4;
   */
  powerSaveStartMinutes: number;

  /**
   * @generated from field: bool apply_power_save_start_minutes = 4001;
   */
  applyPowerSaveStartMinutes: boolean;

  /**
   * @generated from field: uint32 power_save_duration_minutes = 5;
   */
  powerSaveDurationMinutes: number;

  /**
   * @generated from field: bool apply_power_save_duration_minutes = 5001;
   */
  applyPowerSaveDurationMinutes: boolean;

  /**
   * @generated from field: bool power_save_mode = 6;
   */
  powerSaveMode: boolean;

  /**
   * @generated from field: bool apply_power_save_mode = 6001;
   */
  applyPowerSaveMode: boolean;

  /**
   * @generated from field: uint32 swupdate_reboot_hour = 9;
   */
  swupdateRebootHour: number;

  /**
   * @generated from field: bool apply_swupdate_reboot_hour = 9001;
   */
  applySwupdateRebootHour: boolean;

  /**
   * @generated from field: bool swupdate_three_day_deferral_enabled = 7;
   */
  swupdateThreeDayDeferralEnabled: boolean;

  /**
   * @generated from field: bool apply_swupdate_three_day_deferral_enabled = 7001;
   */
  applySwupdateThreeDayDeferralEnabled: boolean;

  /**
   * @generated from field: uint32 asset_class = 8;
   */
  assetClass: number;

  /**
   * @generated from field: bool apply_asset_class = 8001;
   */
  applyAssetClass: boolean;
};

/**
 * Describes the message SpaceX.API.Device.DishConfig.
 * Use `create(DishConfigSchema)` to create a new message.
 */
export const DishConfigSchema: GenMessage<DishConfig> =
  /*@__PURE__*/
  messageDesc(file_spacex_api_device_dish_config, 0);

/**
 * @generated from enum SpaceX.API.Device.DishConfig.SnowMeltMode
 */
export enum DishConfig_SnowMeltMode {
  /**
   * @generated from enum value: AUTO = 0;
   */
  AUTO = 0,

  /**
   * @generated from enum value: ALWAYS_ON = 1;
   */
  ALWAYS_ON = 1,

  /**
   * @generated from enum value: ALWAYS_OFF = 2;
   */
  ALWAYS_OFF = 2,
}

/**
 * Describes the enum SpaceX.API.Device.DishConfig.SnowMeltMode.
 */
export const DishConfig_SnowMeltModeSchema: GenEnum<DishConfig_SnowMeltMode> =
  /*@__PURE__*/
  enumDesc(file_spacex_api_device_dish_config, 0, 0);

/**
 * @generated from enum SpaceX.API.Device.DishConfig.LocationRequestMode
 */
export enum DishConfig_LocationRequestMode {
  /**
   * @generated from enum value: NONE = 0;
   */
  NONE = 0,

  /**
   * @generated from enum value: LOCAL = 1;
   */
  LOCAL = 1,
}

/**
 * Describes the enum SpaceX.API.Device.DishConfig.LocationRequestMode.
 */
export const DishConfig_LocationRequestModeSchema: GenEnum<DishConfig_LocationRequestMode> =
  /*@__PURE__*/
  enumDesc(file_spacex_api_device_dish_config, 0, 1);

/**
 * @generated from enum SpaceX.API.Device.DishConfig.LevelDishMode
 */
export enum DishConfig_LevelDishMode {
  /**
   * @generated from enum value: TILT_LIKE_NORMAL = 0;
   */
  TILT_LIKE_NORMAL = 0,

  /**
   * @generated from enum value: FORCE_LEVEL = 1;
   */
  FORCE_LEVEL = 1,
}

/**
 * Describes the enum SpaceX.API.Device.DishConfig.LevelDishMode.
 */
export const DishConfig_LevelDishModeSchema: GenEnum<DishConfig_LevelDishMode> =
  /*@__PURE__*/
  enumDesc(file_spacex_api_device_dish_config, 0, 2);
