// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file spacex_api/device/rssi_scan.proto (package SpaceX.API.Device, syntax proto3)
 

import type { GenFile, GenMessage } from '@bufbuild/protobuf/codegenv1';
import { fileDesc, messageDesc } from '@bufbuild/protobuf/codegenv1';
import type { Message } from '@bufbuild/protobuf';

/**
 * Describes the file spacex_api/device/rssi_scan.proto.
 */
export const file_spacex_api_device_rssi_scan: GenFile =
  /*@__PURE__*/
  fileDesc(
    'CiFzcGFjZXhfYXBpL2RldmljZS9yc3NpX3NjYW4ucHJvdG8SEVNwYWNlWC5BUEkuRGV2aWNlImIKCVJzc2lFbnRyeRIUCgx0aGV0YV9kZWdyZWUYASABKAESEgoKcGhpX2RlZ3JlZRgCIAEoARIQCghyc3NpX2RiZhgDIAEoARIZChFzY2FuX3RpbWVzdGFtcF9tcxgEIAEoBCInChREaXNoQWN0aXZhdGVSc3NpU2NhbhIPCgdjaGFubmVsGAEgASgNIqQBChVEaXNoR2V0UnNzaVNjYW5SZXN1bHQSDwoHc3VjY2VzcxgBIAEoCBIPCgdjaGFubmVsGAIgASgNEhkKEXJlcXVlc3RfdGltZXN0YW1wGAMgASgEEhYKDm51bWJlcl9zYW1wbGVzGAQgASgNEjYKEHJzc2lfc2Nhbl9wb2ludHMYBSADKAsyHC5TcGFjZVguQVBJLkRldmljZS5Sc3NpRW50cnlCF1oVc3BhY2V4LmNvbS9hcGkvZGV2aWNlYgZwcm90bzM'
  );

/**
 * @generated from message SpaceX.API.Device.RssiEntry
 */
export type RssiEntry = Message<'SpaceX.API.Device.RssiEntry'> & {
  /**
   * @generated from field: double theta_degree = 1;
   */
  thetaDegree: number;

  /**
   * @generated from field: double phi_degree = 2;
   */
  phiDegree: number;

  /**
   * @generated from field: double rssi_dbf = 3;
   */
  rssiDbf: number;

  /**
   * @generated from field: uint64 scan_timestamp_ms = 4;
   */
  scanTimestampMs: bigint;
};

/**
 * Describes the message SpaceX.API.Device.RssiEntry.
 * Use `create(RssiEntrySchema)` to create a new message.
 */
export const RssiEntrySchema: GenMessage<RssiEntry> =
  /*@__PURE__*/
  messageDesc(file_spacex_api_device_rssi_scan, 0);

/**
 * @generated from message SpaceX.API.Device.DishActivateRssiScan
 */
export type DishActivateRssiScan = Message<'SpaceX.API.Device.DishActivateRssiScan'> & {
  /**
   * @generated from field: uint32 channel = 1;
   */
  channel: number;
};

/**
 * Describes the message SpaceX.API.Device.DishActivateRssiScan.
 * Use `create(DishActivateRssiScanSchema)` to create a new message.
 */
export const DishActivateRssiScanSchema: GenMessage<DishActivateRssiScan> =
  /*@__PURE__*/
  messageDesc(file_spacex_api_device_rssi_scan, 1);

/**
 * @generated from message SpaceX.API.Device.DishGetRssiScanResult
 */
export type DishGetRssiScanResult = Message<'SpaceX.API.Device.DishGetRssiScanResult'> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: uint32 channel = 2;
   */
  channel: number;

  /**
   * @generated from field: uint64 request_timestamp = 3;
   */
  requestTimestamp: bigint;

  /**
   * @generated from field: uint32 number_samples = 4;
   */
  numberSamples: number;

  /**
   * @generated from field: repeated SpaceX.API.Device.RssiEntry rssi_scan_points = 5;
   */
  rssiScanPoints: RssiEntry[];
};

/**
 * Describes the message SpaceX.API.Device.DishGetRssiScanResult.
 * Use `create(DishGetRssiScanResultSchema)` to create a new message.
 */
export const DishGetRssiScanResultSchema: GenMessage<DishGetRssiScanResult> =
  /*@__PURE__*/
  messageDesc(file_spacex_api_device_rssi_scan, 2);
