// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file spacex_api/common/status/status.proto (package SpaceX.API.Status, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spacex_api/common/status/status.proto.
 */
export const file_spacex_api_common_status_status: GenFile = /*@__PURE__*/
  fileDesc("CiVzcGFjZXhfYXBpL2NvbW1vbi9zdGF0dXMvc3RhdHVzLnByb3RvEhFTcGFjZVguQVBJLlN0YXR1cyInCgZTdGF0dXMSDAoEY29kZRgBIAEoBRIPCgdtZXNzYWdlGAIgASgJQhdaFXNwYWNleC5jb20vYXBpL3N0YXR1c2IGcHJvdG8z");

/**
 * @generated from message SpaceX.API.Status.Status
 */
export type Status = Message<"SpaceX.API.Status.Status"> & {
  /**
   * @generated from field: int32 code = 1;
   */
  code: number;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message SpaceX.API.Status.Status.
 * Use `create(StatusSchema)` to create a new message.
 */
export const StatusSchema: GenMessage<Status> = /*@__PURE__*/
  messageDesc(file_spacex_api_common_status_status, 0);

