// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file spacex_api/telemetron/public/common/time.proto (package SpaceX.API.Telemetron.Public.Common, syntax proto3)

import type { GenEnum, GenFile, GenMessage } from '@bufbuild/protobuf/codegenv1';
import { enumDesc, fileDesc, messageDesc } from '@bufbuild/protobuf/codegenv1';
import type { Message } from '@bufbuild/protobuf';

/**
 * Describes the file spacex_api/telemetron/public/common/time.proto.
 */
export const file_spacex_api_telemetron_public_common_time: GenFile =
  /*@__PURE__*/
  fileDesc(
    'Ci5zcGFjZXhfYXBpL3RlbGVtZXRyb24vcHVibGljL2NvbW1vbi90aW1lLnByb3RvEiNTcGFjZVguQVBJLlRlbGVtZXRyb24uUHVibGljLkNvbW1vbiJfCg1UaW1lc3RhbXBJbmZvEjkKBWVwb2NoGAEgASgOMiouU3BhY2VYLkFQSS5UZWxlbWV0cm9uLlB1YmxpYy5Db21tb24uRXBvY2gSEwoLbmFub3NlY29uZHMYAiABKAMqGgoFRXBvY2gSCAoEVU5JWBAAEgcKA0dQUxABYgZwcm90bzM'
  );

/**
 * @generated from message SpaceX.API.Telemetron.Public.Common.TimestampInfo
 */
export type TimestampInfo = Message<'SpaceX.API.Telemetron.Public.Common.TimestampInfo'> & {
  /**
   * @generated from field: SpaceX.API.Telemetron.Public.Common.Epoch epoch = 1;
   */
  epoch: Epoch;

  /**
   * @generated from field: int64 nanoseconds = 2;
   */
  nanoseconds: bigint;
};

/**
 * Describes the message SpaceX.API.Telemetron.Public.Common.TimestampInfo.
 * Use `create(TimestampInfoSchema)` to create a new message.
 */
export const TimestampInfoSchema: GenMessage<TimestampInfo> =
  /*@__PURE__*/
  messageDesc(file_spacex_api_telemetron_public_common_time, 0);

/**
 * @generated from enum SpaceX.API.Telemetron.Public.Common.Epoch
 */
export enum Epoch {
  /**
   * @generated from enum value: UNIX = 0;
   */
  UNIX = 0,

  /**
   * @generated from enum value: GPS = 1;
   */
  GPS = 1,
}

/**
 * Describes the enum SpaceX.API.Telemetron.Public.Common.Epoch.
 */
export const EpochSchema: GenEnum<Epoch> =
  /*@__PURE__*/
  enumDesc(file_spacex_api_telemetron_public_common_time, 0);
