// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file spacex_api/satellites/network/ut_disablement_codes.proto (package SpaceX.API.Satellites.Network, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file spacex_api/satellites/network/ut_disablement_codes.proto.
 */
export const file_spacex_api_satellites_network_ut_disablement_codes: GenFile = /*@__PURE__*/
  fileDesc("CjhzcGFjZXhfYXBpL3NhdGVsbGl0ZXMvbmV0d29yay91dF9kaXNhYmxlbWVudF9jb2Rlcy5wcm90bxIdU3BhY2VYLkFQSS5TYXRlbGxpdGVzLk5ldHdvcmsqowMKEVV0RGlzYWJsZW1lbnRDb2RlEhEKDVVOS05PV05fU1RBVEUQABIICgRPS0FZEAESFQoRTk9fQUNUSVZFX0FDQ09VTlQQAhIgChxUT09fRkFSX0ZST01fU0VSVklDRV9BRERSRVNTEAMSDAoISU5fT0NFQU4QBBITCg9CTE9DS0VEX0NPVU5UUlkQBhIfChtEQVRBX09WRVJBR0VfU0FOREJPWF9QT0xJQ1kQBxIUChBDRUxMX0lTX0RJU0FCTEVEEAgSEwoPUk9BTV9SRVNUUklDVEVEEAoSFAoQVU5LTk9XTl9MT0NBVElPThALEhQKEEFDQ09VTlRfRElTQUJMRUQQDBIXChNVTlNVUFBPUlRFRF9WRVJTSU9OEA0SHgoaTU9WSU5HX1RPT19GQVNUX0ZPUl9QT0xJQ1kQDhIhCh1VTkRFUl9BVklBVElPTl9GTFlPVkVSX0xJTUlUUxAPEhAKDEJMT0NLRURfQVJFQRAQIgQIBRAFIgQICRAJKg9JTlZBTElEX0NPVU5UUlkqElVOTElDRU5TRURfQ09VTlRSWSpPChhBY2NvdW50RGlzYWJsZW1lbnRSZWFzb24SEgoOTk9fUkVTVFJJQ1RJT04QABIfChtLTk9XX1lPVVJfQ1VTVE9NRVJfUkVRVUlSRUQQAWIGcHJvdG8z");

/**
 * @generated from enum SpaceX.API.Satellites.Network.UtDisablementCode
 */
export enum UtDisablementCode {
  /**
   * @generated from enum value: UNKNOWN_STATE = 0;
   */
  UNKNOWN_STATE = 0,

  /**
   * @generated from enum value: OKAY = 1;
   */
  OKAY = 1,

  /**
   * @generated from enum value: NO_ACTIVE_ACCOUNT = 2;
   */
  NO_ACTIVE_ACCOUNT = 2,

  /**
   * @generated from enum value: TOO_FAR_FROM_SERVICE_ADDRESS = 3;
   */
  TOO_FAR_FROM_SERVICE_ADDRESS = 3,

  /**
   * @generated from enum value: IN_OCEAN = 4;
   */
  IN_OCEAN = 4,

  /**
   * @generated from enum value: BLOCKED_COUNTRY = 6;
   */
  BLOCKED_COUNTRY = 6,

  /**
   * @generated from enum value: DATA_OVERAGE_SANDBOX_POLICY = 7;
   */
  DATA_OVERAGE_SANDBOX_POLICY = 7,

  /**
   * @generated from enum value: CELL_IS_DISABLED = 8;
   */
  CELL_IS_DISABLED = 8,

  /**
   * @generated from enum value: ROAM_RESTRICTED = 10;
   */
  ROAM_RESTRICTED = 10,

  /**
   * @generated from enum value: UNKNOWN_LOCATION = 11;
   */
  UNKNOWN_LOCATION = 11,

  /**
   * @generated from enum value: ACCOUNT_DISABLED = 12;
   */
  ACCOUNT_DISABLED = 12,

  /**
   * @generated from enum value: UNSUPPORTED_VERSION = 13;
   */
  UNSUPPORTED_VERSION = 13,

  /**
   * @generated from enum value: MOVING_TOO_FAST_FOR_POLICY = 14;
   */
  MOVING_TOO_FAST_FOR_POLICY = 14,

  /**
   * @generated from enum value: UNDER_AVIATION_FLYOVER_LIMITS = 15;
   */
  UNDER_AVIATION_FLYOVER_LIMITS = 15,

  /**
   * @generated from enum value: BLOCKED_AREA = 16;
   */
  BLOCKED_AREA = 16,
}

/**
 * Describes the enum SpaceX.API.Satellites.Network.UtDisablementCode.
 */
export const UtDisablementCodeSchema: GenEnum<UtDisablementCode> = /*@__PURE__*/
  enumDesc(file_spacex_api_satellites_network_ut_disablement_codes, 0);

/**
 * @generated from enum SpaceX.API.Satellites.Network.AccountDisablementReason
 */
export enum AccountDisablementReason {
  /**
   * @generated from enum value: NO_RESTRICTION = 0;
   */
  NO_RESTRICTION = 0,

  /**
   * @generated from enum value: KNOW_YOUR_CUSTOMER_REQUIRED = 1;
   */
  KNOW_YOUR_CUSTOMER_REQUIRED = 1,
}

/**
 * Describes the enum SpaceX.API.Satellites.Network.AccountDisablementReason.
 */
export const AccountDisablementReasonSchema: GenEnum<AccountDisablementReason> = /*@__PURE__*/
  enumDesc(file_spacex_api_satellites_network_ut_disablement_codes, 1);

