// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file spacex_api/telemetron/public/integrations/rate_limit_reason.proto (package SpaceX.API.Telemetron.Public.Integrations, syntax proto3)

import type { GenEnum, GenFile } from '@bufbuild/protobuf/codegenv1';
import { enumDesc, fileDesc } from '@bufbuild/protobuf/codegenv1';

/**
 * Describes the file spacex_api/telemetron/public/integrations/rate_limit_reason.proto.
 */
export const file_spacex_api_telemetron_public_integrations_rate_limit_reason: GenFile =
  /*@__PURE__*/
  fileDesc(
    'CkFzcGFjZXhfYXBpL3RlbGVtZXRyb24vcHVibGljL2ludGVncmF0aW9ucy9yYXRlX2xpbWl0X3JlYXNvbi5wcm90bxIpU3BhY2VYLkFQSS5UZWxlbWV0cm9uLlB1YmxpYy5JbnRlZ3JhdGlvbnMqhQEKD1JhdGVMaW1pdFJlYXNvbhILCgdVTktOT1dOEAASDAoITk9fTElNSVQQARIQCgxQT0xJQ1lfTElNSVQQAhIVChFVU0VSX0NVU1RPTV9MSU1JVBADEhEKDU9WRVJBR0VfTElNSVQQBSIECAQQBCoVSElHSF9IT1VSTFlfQVZHX0xJTUlUQj9aPXNwYWNleC5jb20vYXBpL3RlbGVtZXRyb24vcHVibGljL2ludGVncmF0aW9ucy9yYXRlbGltaXRyZWFzb25iBnByb3RvMw'
  );

/**
 * @generated from enum SpaceX.API.Telemetron.Public.Integrations.RateLimitReason
 */
export enum RateLimitReason {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: NO_LIMIT = 1;
   */
  NO_LIMIT = 1,

  /**
   * @generated from enum value: POLICY_LIMIT = 2;
   */
  POLICY_LIMIT = 2,

  /**
   * @generated from enum value: USER_CUSTOM_LIMIT = 3;
   */
  USER_CUSTOM_LIMIT = 3,

  /**
   * @generated from enum value: OVERAGE_LIMIT = 5;
   */
  OVERAGE_LIMIT = 5,
}

/**
 * Describes the enum SpaceX.API.Telemetron.Public.Integrations.RateLimitReason.
 */
export const RateLimitReasonSchema: GenEnum<RateLimitReason> =
  /*@__PURE__*/
  enumDesc(file_spacex_api_telemetron_public_integrations_rate_limit_reason, 0);
