// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file spacex_api/device/services/unlock/service.proto (package SpaceX.API.Device.Services.Unlock, syntax proto3)
 

import type { GenFile, GenMessage, GenService } from '@bufbuild/protobuf/codegenv1';
import { fileDesc, messageDesc, serviceDesc } from '@bufbuild/protobuf/codegenv1';
import type { Message } from '@bufbuild/protobuf';

/**
 * Describes the file spacex_api/device/services/unlock/service.proto.
 */
export const file_spacex_api_device_services_unlock_service: GenFile =
  /*@__PURE__*/
  fileDesc(
    'Ci9zcGFjZXhfYXBpL2RldmljZS9zZXJ2aWNlcy91bmxvY2svc2VydmljZS5wcm90bxIhU3BhY2VYLkFQSS5EZXZpY2UuU2VydmljZXMuVW5sb2NrIqIBCg9VbmxvY2tDaGFsbGVuZ2USEQoJZGV2aWNlX2lkGAEgASgJEg0KBW5vbmNlGAIgASgMEhEKCXNpZ25fc3BraRgEIAEoDBIVCg1ncmFudF9rZXlkYXRhGAUgASgJEhcKD3NlcnZpY2Vfa2V5ZGF0YRgGIAEoCRIYChBhdXRob3JpdHlfZ3JhbnRzGAcgAygJSgQIAxAEUgpncmFudF9zcGtpIhQKElN0YXJ0VW5sb2NrUmVxdWVzdCJKChNTdGFydFVubG9ja1Jlc3BvbnNlEhEKCWRldmljZV9pZBgBIAEoCRINCgVub25jZRgCIAEoDBIRCglzaWduX3Nwa2kYAyABKAwiOwoTRmluaXNoVW5sb2NrUmVxdWVzdBIRCgljaGFsbGVuZ2UYASABKAwSEQoJc2lnbmF0dXJlGAIgASgMIiYKFEZpbmlzaFVubG9ja1Jlc3BvbnNlEg4KBnN0YXR1cxgBIAEoDTKOAgoNVW5sb2NrU2VydmljZRJ8CgtTdGFydFVubG9jaxI1LlNwYWNlWC5BUEkuRGV2aWNlLlNlcnZpY2VzLlVubG9jay5TdGFydFVubG9ja1JlcXVlc3QaNi5TcGFjZVguQVBJLkRldmljZS5TZXJ2aWNlcy5VbmxvY2suU3RhcnRVbmxvY2tSZXNwb25zZRJ/CgxGaW5pc2hVbmxvY2sSNi5TcGFjZVguQVBJLkRldmljZS5TZXJ2aWNlcy5VbmxvY2suRmluaXNoVW5sb2NrUmVxdWVzdBo3LlNwYWNlWC5BUEkuRGV2aWNlLlNlcnZpY2VzLlVubG9jay5GaW5pc2hVbmxvY2tSZXNwb25zZWIGcHJvdG8z'
  );

/**
 * @generated from message SpaceX.API.Device.Services.Unlock.UnlockChallenge
 */
export type UnlockChallenge = Message<'SpaceX.API.Device.Services.Unlock.UnlockChallenge'> & {
  /**
   * @generated from field: string device_id = 1;
   */
  deviceId: string;

  /**
   * @generated from field: bytes nonce = 2;
   */
  nonce: Uint8Array;

  /**
   * @generated from field: bytes sign_spki = 4;
   */
  signSpki: Uint8Array;

  /**
   * @generated from field: string grant_keydata = 5;
   */
  grantKeydata: string;

  /**
   * @generated from field: string service_keydata = 6;
   */
  serviceKeydata: string;

  /**
   * @generated from field: repeated string authority_grants = 7;
   */
  authorityGrants: string[];
};

/**
 * Describes the message SpaceX.API.Device.Services.Unlock.UnlockChallenge.
 * Use `create(UnlockChallengeSchema)` to create a new message.
 */
export const UnlockChallengeSchema: GenMessage<UnlockChallenge> =
  /*@__PURE__*/
  messageDesc(file_spacex_api_device_services_unlock_service, 0);

/**
 * @generated from message SpaceX.API.Device.Services.Unlock.StartUnlockRequest
 */
export type StartUnlockRequest =
  Message<'SpaceX.API.Device.Services.Unlock.StartUnlockRequest'> & {};

/**
 * Describes the message SpaceX.API.Device.Services.Unlock.StartUnlockRequest.
 * Use `create(StartUnlockRequestSchema)` to create a new message.
 */
export const StartUnlockRequestSchema: GenMessage<StartUnlockRequest> =
  /*@__PURE__*/
  messageDesc(file_spacex_api_device_services_unlock_service, 1);

/**
 * @generated from message SpaceX.API.Device.Services.Unlock.StartUnlockResponse
 */
export type StartUnlockResponse =
  Message<'SpaceX.API.Device.Services.Unlock.StartUnlockResponse'> & {
    /**
     * @generated from field: string device_id = 1;
     */
    deviceId: string;

    /**
     * @generated from field: bytes nonce = 2;
     */
    nonce: Uint8Array;

    /**
     * @generated from field: bytes sign_spki = 3;
     */
    signSpki: Uint8Array;
  };

/**
 * Describes the message SpaceX.API.Device.Services.Unlock.StartUnlockResponse.
 * Use `create(StartUnlockResponseSchema)` to create a new message.
 */
export const StartUnlockResponseSchema: GenMessage<StartUnlockResponse> =
  /*@__PURE__*/
  messageDesc(file_spacex_api_device_services_unlock_service, 2);

/**
 * @generated from message SpaceX.API.Device.Services.Unlock.FinishUnlockRequest
 */
export type FinishUnlockRequest =
  Message<'SpaceX.API.Device.Services.Unlock.FinishUnlockRequest'> & {
    /**
     * @generated from field: bytes challenge = 1;
     */
    challenge: Uint8Array;

    /**
     * @generated from field: bytes signature = 2;
     */
    signature: Uint8Array;
  };

/**
 * Describes the message SpaceX.API.Device.Services.Unlock.FinishUnlockRequest.
 * Use `create(FinishUnlockRequestSchema)` to create a new message.
 */
export const FinishUnlockRequestSchema: GenMessage<FinishUnlockRequest> =
  /*@__PURE__*/
  messageDesc(file_spacex_api_device_services_unlock_service, 3);

/**
 * @generated from message SpaceX.API.Device.Services.Unlock.FinishUnlockResponse
 */
export type FinishUnlockResponse =
  Message<'SpaceX.API.Device.Services.Unlock.FinishUnlockResponse'> & {
    /**
     * @generated from field: uint32 status = 1;
     */
    status: number;
  };

/**
 * Describes the message SpaceX.API.Device.Services.Unlock.FinishUnlockResponse.
 * Use `create(FinishUnlockResponseSchema)` to create a new message.
 */
export const FinishUnlockResponseSchema: GenMessage<FinishUnlockResponse> =
  /*@__PURE__*/
  messageDesc(file_spacex_api_device_services_unlock_service, 4);

/**
 * @generated from service SpaceX.API.Device.Services.Unlock.UnlockService
 */
export const UnlockService: GenService<{
  /**
   * @generated from rpc SpaceX.API.Device.Services.Unlock.UnlockService.StartUnlock
   */
  startUnlock: {
    methodKind: 'unary';
    input: typeof StartUnlockRequestSchema;
    output: typeof StartUnlockResponseSchema;
  };
  /**
   * @generated from rpc SpaceX.API.Device.Services.Unlock.UnlockService.FinishUnlock
   */
  finishUnlock: {
    methodKind: 'unary';
    input: typeof FinishUnlockRequestSchema;
    output: typeof FinishUnlockResponseSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_spacex_api_device_services_unlock_service, 0);
